// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Github': typeof import("../components/Github.vue")['default'],
    'Home': typeof import("../components/Home.vue")['default'],
    'Linkedin': typeof import("../components/Linkedin.vue")['default'],
    'Twitter': typeof import("../components/Twitter.vue")['default'],
    'SocialInstagram': typeof import("../components/social/Instagram.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyGithub': typeof import("../components/Github.vue")['default'],
    'LazyHome': typeof import("../components/Home.vue")['default'],
    'LazyLinkedin': typeof import("../components/Linkedin.vue")['default'],
    'LazyTwitter': typeof import("../components/Twitter.vue")['default'],
    'LazySocialInstagram': typeof import("../components/social/Instagram.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Footer: typeof import("../components/Footer.vue")['default']
export const Github: typeof import("../components/Github.vue")['default']
export const Home: typeof import("../components/Home.vue")['default']
export const Linkedin: typeof import("../components/Linkedin.vue")['default']
export const Twitter: typeof import("../components/Twitter.vue")['default']
export const SocialInstagram: typeof import("../components/social/Instagram.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyGithub: typeof import("../components/Github.vue")['default']
export const LazyHome: typeof import("../components/Home.vue")['default']
export const LazyLinkedin: typeof import("../components/Linkedin.vue")['default']
export const LazyTwitter: typeof import("../components/Twitter.vue")['default']
export const LazySocialInstagram: typeof import("../components/social/Instagram.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
